name: testing env

on: workflow_dispatch

env:
  DEVELOPER_DIR: /Applications/Xcode_13.1/developer/

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - run: |-
          echo "dev dir is: $DEVELOPER_DIR"
      - uses: ./.github/actions/set-env
      - run: |-
          echo "dev dir is: $DEVELOPER_DIR"

